project_id = "vmpenssdavqqhmhdejok"

[functions.categorize-transaction]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false

[functions.parse-transaction]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false
